const data = [
  {
    name: "The Evil Queen",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_The_Evil_Queen.webp`,
    films: [
      "Snow White and the Seven Dwarfs",
      "Who Framed Roger Rabbit (cameo)",
      "Golden Anniversary of Snow White and the Seven Dwarfs",
      "The Nightmare Before Christmas (cameo)",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Mickey's House of Villains",
      "Once Upon a Halloween",
      "Pinocchio (2022) (cameo)",
    ],
    year: "1937",
  },
  {
    name: "Chernabog",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Chernabog.webp`,
    films: [
      "Fantasia",
      "The Reluctant Dragon (cameo)",
      "Fantasia 2000 (appeared in a flashback)",
      "Mickey's House of Villains",
      "Once Upon a Halloween",
      "The Sorcerer's Apprentice (as a statue)",
    ],
    year: "1940",
  },
  {
    name: "Queen of Hearts",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Queen_of_Hearts.webp`,
    films: [
      "Alice in Wonderland",
      "Mickey's House of Villains",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Once Upon a Halloween",
    ],
    year: "1951",
  },
  {
    name: "Captain Hook",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Captain_Hook.webp`,
    films: [
      "Peter Pan",
      "Return to Never Land",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Mickey's House of Villains",
      "Once Upon a Halloween",
    ],
    year: "1953",
  },
  {
    name: "Maleficent",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Maleficent.webp`,
    films: [
      "Sleeping Beauty",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Mickey's House of Villains",
      "Once Upon a Halloween",
      "Pinocchio (2022) (cameo)",
    ],
    year: "1959",
  },
  {
    name: "Cruella De Vil",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Cruella.webp`,
    films: [
      "One Hundred and One Dalmatians",
      "Mickey's House of Villains",
      "101 Dalmatians II: Patch's London Adventure",
      "Once Upon a Halloween",
    ],
    year: "1961",
  },
  {
    name: "Ursula",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Ursula.webp`,
    films: [
      "The Little Mermaid",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Mickey's House of Villains",
      "Once Upon a Halloween",
    ],
    year: "1989",
  },
  {
    name: "Jafar",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Jafar.webp`,
    films: [
      "Aladdin",
      "The Return of Jafar",
      "Aladdin and the King of Thieves (cameo)",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Mickey's House of Villains",
      "Once Upon a Halloween",
    ],
    year: "1992",
  },
  {
    name: "Scar",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Scar.webp`,
    films: [
      "The Lion King",
      "The Lion King II: Simba's Pride",
      "The Lion King 1½",
      "Hercules (cameo)",
      "Once Upon a Halloween",
      "The Lion Guard: Return of the Roar (cameo)",
    ],
    year: "1994",
  },
  {
    name: "Hades",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Hades.webp`,
    films: [
      "Hercules",
      "Hercules: Zero to Hero",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Mickey's House of Villains",
      "Once Upon a Halloween",
      "Descendants 3",
      "Descendants: The Royal Wedding",
      "Descendants: The Rise of Red",
    ],
    year: "1997",
  },
  {
    name: "Dr. Facilier",
    image: `${process.env.BASE_URL}/resources/disney-villians/Profile_-_Dr._Facilier.webp`,
    films: ["The Princess and the Frog"],
    year: "2009",
  },
];

module.exports = data;
